import type { HelpContent } from './ContextHelp.js';

function h(
  titleEn: string,
  titleFa: string,
  summaryEn: string,
  summaryFa: string,
  whyEn?: string,
  whyFa?: string,
  calculationEn?: string,
  calculationFa?: string,
): HelpContent {
  return {
    title: { en: titleEn, fa: titleFa },
    summary: { en: summaryEn, fa: summaryFa },
    ...(whyEn && whyFa ? { why: { en: whyEn, fa: whyFa } } : {}),
    ...(calculationEn && calculationFa
      ? { calculation: { en: calculationEn, fa: calculationFa } }
      : {}),
  };
}

export const HELP = {
  navigation: {
    overview: h(
      'Overview',
      'نمای کلی',
      'A compact operational summary of the selected PBX: current health, live calls, infrastructure and active problems.',
      'خلاصه عملیاتی PBX انتخاب‌شده را نشان می‌دهد: سلامت فعلی، تماس‌های زنده، زیرساخت و مشکلات جاری.',
      'Use it as the first screen for situational awareness before opening a detailed workspace.',
      'برای دید اولیه از وضعیت سیستم استفاده کنید و بعد در صورت نیاز وارد صفحه تخصصی شوید.',
    ),
    operations: h(
      'Operations',
      'عملیات',
      'Contains live telephony views and source-backed reports.',
      'نماهای زنده تلفنی و گزارش‌های مبتنی بر داده منبع را در خود دارد.',
      'Operational pages are read-only monitoring views; they do not place or modify calls.',
      'صفحات عملیات فقط برای مانیتورینگ خواندنی هستند و تماس ایجاد یا تغییر نمی‌دهند.',
    ),
    settings: h(
      'Settings',
      'تنظیمات',
      'Contains PBX connections, data sources, infrastructure, security and dashboard configuration.',
      'اتصال PBX، منبع داده، زیرساخت، امنیت و تنظیمات داشبورد را مدیریت می‌کند.',
      'Settings change how the monitor connects to or presents sources, so verify scope before saving.',
      'تنظیمات نحوه اتصال یا نمایش منابع را تغییر می‌دهند؛ قبل از ذخیره محدوده را بررسی کنید.',
    ),
    fleet: h(
      'PBX Fleet',
      'فهرست PBXها',
      'Shows all configured PBX instances and their monitoring status.',
      'همه PBXهای تعریف‌شده و وضعیت مانیتورینگ آن‌ها را نشان می‌دهد.',
      'Use it to choose which PBX needs attention without opening each instance separately.',
      'برای پیدا کردن سریع PBX نیازمند توجه بدون باز کردن تک‌تک سیستم‌ها استفاده می‌شود.',
    ),
    liveCalls: h(
      'Live Calls',
      'تماس‌های زنده',
      'Shows calls currently known to the normalized telephony state.',
      'تماس‌هایی را نشان می‌دهد که در وضعیت نرمال‌شده تلفنی اکنون فعال هستند.',
      'Useful for real-time observation; it is not historical call reporting.',
      'برای مشاهده لحظه‌ای مفید است و جای گزارش تاریخی تماس‌ها را نمی‌گیرد.',
    ),
    channels: h(
      'Channels',
      'Channelها',
      'Shows active Asterisk channel state exposed by the provider.',
      'وضعیت Channelهای فعال Asterisk را که Provider گزارش می‌کند نمایش می‌دهد.',
      'Channels are lower-level call legs and may outnumber human calls.',
      'Channel سطح پایین‌تری از Call است و ممکن است تعداد آن از تماس‌های انسانی بیشتر باشد.',
    ),
    trunks: h(
      'Trunks',
      'Trunkها',
      'Shows discovered trunk connectivity and reliability signals.',
      'وضعیت اتصال و شاخص‌های پایداری Trunkهای شناسایی‌شده را نشان می‌دهد.',
      'Use it to separate carrier/trunk availability problems from endpoint or queue issues.',
      'کمک می‌کند مشکل Carrier/Trunk از مشکل Endpoint یا Queue جدا شود.',
    ),
    endpoints: h(
      'Endpoints',
      'Endpointها',
      'Shows endpoint reachability, registration and reliability state when available.',
      'وضعیت دسترس‌پذیری، Registration و پایداری Endpointها را در صورت وجود نشان می‌دهد.',
      'Useful for identifying phones/devices that are currently unreachable or unstable.',
      'برای پیدا کردن تلفن‌ها یا دستگاه‌های غیرقابل‌دسترس یا ناپایدار استفاده می‌شود.',
    ),
    queues: h(
      'Queues',
      'صف‌ها',
      'Shows current normalized queue state from the telephony provider.',
      'وضعیت جاری و نرمال‌شده صف‌ها را از Provider تلفنی نمایش می‌دهد.',
      'This is a live view; historical queue performance is available under Reports.',
      'این نمای لحظه‌ای است؛ تحلیل تاریخی عملکرد صف در بخش گزارش‌ها قرار دارد.',
    ),
    agents: h(
      'Agents',
      'Agentها',
      'Shows current queue-agent state when the PBX exposes it.',
      'وضعیت فعلی Agentهای صف را در صورت ارائه توسط PBX نشان می‌دهد.',
      'Use it to understand current staffing/availability, not long-term agent performance.',
      'برای درک وضعیت فعلی نیروها و دسترس‌پذیری است، نه ارزیابی بلندمدت عملکرد Agent.',
    ),
    reports: h(
      'Reports',
      'گزارشات',
      'Builds source-backed historical reports without creating a duplicate monitoring warehouse.',
      'گزارش‌های تاریخی را مستقیماً از منبع می‌سازد بدون اینکه انبار داده تکراری در مانیتور ایجاد شود.',
      'Reports explain historical behavior; live pages explain what is happening now.',
      'گزارش‌ها رفتار گذشته را توضیح می‌دهند و صفحات Live وضعیت همین لحظه را.',
    ),
    pbxSettings: h(
      'PBX settings',
      'تنظیمات PBX',
      'Configures the monitored PBX identity and AMI connection.',
      'هویت PBX مانیتورشده و اتصال AMI را تنظیم می‌کند.',
      'AMI is used for live telephony monitoring; credentials are kept outside public repository content.',
      'AMI برای مانیتورینگ زنده استفاده می‌شود و Credentialها خارج از محتوای عمومی Repository نگهداری می‌شوند.',
    ),
    dataSource: h(
      'Data source',
      'منبع داده',
      'Configures the read-only historical database source used by Reports.',
      'منبع دیتابیس فقط‌خواندنی مورد استفاده گزارش‌ها را تنظیم می‌کند.',
      'Historical reports stay source-owned; the monitor does not duplicate call-history storage.',
      'داده تاریخی در منبع اصلی می‌ماند و مانیتور نسخه تکراری از تاریخچه تماس ذخیره نمی‌کند.',
    ),
    infrastructure: h(
      'Infrastructure',
      'زیرساخت',
      'Configures restricted infrastructure access used for system metrics.',
      'دسترسی محدود زیرساخت را برای دریافت System Metricها تنظیم می‌کند.',
      'This separates host monitoring from telephony signaling and keeps access least-privilege.',
      'مانیتورینگ Host را از Signaling تلفنی جدا می‌کند و سطح دسترسی را حداقلی نگه می‌دارد.',
    ),
    serviceMonitoring: h(
      'Service monitoring',
      'مانیتورینگ سرویس',
      'Controls monitoring of selected operating-system services.',
      'پایش سرویس‌های انتخاب‌شده سیستم‌عامل را کنترل می‌کند.',
      'Useful for detecting application/service failures even when the host itself is reachable.',
      'برای تشخیص خرابی سرویس کاربردی است حتی وقتی خود Host در دسترس باشد.',
    ),
    storage: h(
      'Storage / filesystems',
      'Storage / Filesystems',
      'Selects which filesystems are meaningful enough to show on the dashboard.',
      'مشخص می‌کند کدام Filesystemها ارزش نمایش روی داشبورد را دارند.',
      'Hiding ephemeral mounts keeps storage alerts focused on real operational capacity.',
      'پنهان‌کردن Mountهای موقت باعث می‌شود هشدار Storage روی ظرفیت‌های واقعاً عملیاتی متمرکز بماند.',
    ),
    dashboardSettings: h(
      'Dashboard settings',
      'تنظیمات داشبورد',
      'Controls presentation refresh cadence for dashboard elements.',
      'نرخ به‌روزرسانی نمایشی اجزای داشبورد را کنترل می‌کند.',
      'These settings change presentation cadence, not the underlying source collection policy.',
      'این تنظیمات فقط سرعت نمایش را تغییر می‌دهند و سیاست جمع‌آوری داده منبع را عوض نمی‌کنند.',
    ),
    security: h(
      'Security monitoring',
      'پایش امنیت',
      'Shows bounded security alerts produced by the configured monitoring rules.',
      'هشدارهای امنیتی محدودشده‌ای را که Ruleهای مانیتورینگ تولید کرده‌اند نمایش می‌دهد.',
      'Use it for operational awareness; it is not a full SIEM replacement.',
      'برای آگاهی عملیاتی است و جایگزین کامل SIEM محسوب نمی‌شود.',
    ),
    accounts: h(
      'Accounts',
      'حساب‌های کاربری',
      'Manages application users and access to the monitor.',
      'کاربران برنامه و دسترسی به مانیتور را مدیریت می‌کند.',
      'Account controls affect who can view or change monitoring configuration.',
      'کنترل حساب‌ها مشخص می‌کند چه کسی می‌تواند مانیتورینگ را مشاهده یا تنظیم کند.',
    ),
  },

  reports: {
    guide: h(
      'How to read these reports',
      'راهنمای خواندن گزارش‌ها',
      'Every ? icon explains what a field or KPI means, why it exists and, for report metrics, how it is calculated.',
      'کنار هر فیلد یا KPI علامت ؟ قرار دارد که می‌گوید آن مورد چیست، چرا وجود دارد و در گزارش‌ها چگونه محاسبه می‌شود.',
      'A large call count does not necessarily mean the same number of people. Call volume and unique callers are intentionally separate KPIs.',
      'تعداد زیاد تماس الزاماً به معنی همان تعداد فرد نیست. حجم تماس و تماس‌گیرنده یکتا عمداً دو KPI جدا هستند.',
      'Queue reports use source-side aggregates. Caller identity KPIs deduplicate caller IDs in memory using temporary pseudonymous digests; no caller identity is persisted by the managerial report.',
      'گزارش صف از Aggregateهای سمت Source استفاده می‌کند. KPIهای هویتی Caller با شناسه موقت و ناشناس در حافظه Deduplicate می‌شوند و هویت تماس‌گیرنده در گزارش مدیریتی ذخیره نمی‌شود.',
    ),
    from: h(
      'From date and time',
      'از تاریخ و ساعت',
      'Start of the source-local reporting window.',
      'ابتدای بازه زمانی گزارش بر اساس زمان محلی Source.',
      'All selected queue events before this timestamp are excluded.',
      'تمام Eventهای صف قبل از این زمان از گزارش خارج می‌شوند.',
      'Filter: event time >= From.',
      'فیلتر: زمان Event بزرگ‌تر یا مساوی From است.',
    ),
    to: h(
      'To date and time',
      'تا تاریخ و ساعت',
      'End of the source-local reporting window.',
      'انتهای بازه زمانی گزارش بر اساس زمان محلی Source.',
      'Choosing a precise end time makes period-to-period comparisons repeatable.',
      'انتخاب زمان پایان دقیق باعث می‌شود مقایسه دوره‌ها قابل تکرار باشد.',
      'The final source chunk includes events up to the selected To time; earlier chunks use non-overlapping half-open boundaries.',
      'Chunk نهایی Eventها را تا زمان To شامل می‌شود و Chunkهای قبلی مرزهای بدون هم‌پوشانی دارند.',
    ),
    queues: h(
      'Selected queues',
      'صف‌های انتخاب‌شده',
      'Chooses which queue IDs are included in the report.',
      'مشخص می‌کند کدام Queue IDها داخل گزارش باشند.',
      'Per-queue rows and a combined total are returned together so queue behavior can be compared without losing the overall picture.',
      'هم ردیف تفکیکی هر صف و هم Total مشترک نمایش داده می‌شود تا مقایسه صف‌ها همراه با تصویر کلی ممکن باشد.',
      'The report accepts 1–16 queue IDs. Combined caller KPIs deduplicate the same caller across all selected queues.',
      'گزارش بین ۱ تا ۱۶ صف را می‌پذیرد. KPIهای Caller در Total، یک تماس‌گیرنده مشترک بین صف‌ها را فقط یک بار می‌شمارند.',
    ),
    incoming: h(
      'Incoming queue calls',
      'تماس‌های ورودی صف',
      'Number of queue-entry events in the selected queues and time window.',
      'تعداد Eventهای ورود به صف در صف‌ها و بازه انتخاب‌شده.',
      'This measures queue workload. It is call volume, not the number of different people.',
      'این KPI حجم کار صف را نشان می‌دهد و تعداد تماس است، نه تعداد افراد متفاوت.',
      'Count of ENTERQUEUE events. Combined total is the sum of entries across selected queues.',
      'از شمارش Eventهای ENTERQUEUE به‌دست می‌آید. Total مجموع ورودها در صف‌های انتخاب‌شده است.',
    ),
    answered: h(
      'Answered calls',
      'تماس‌های پاسخ‌داده‌شده',
      'Calls that reached a queue-agent CONNECT event in the selected window.',
      'تماس‌هایی که در بازه انتخاب‌شده به Event اتصال به Agent یعنی CONNECT رسیده‌اند.',
      'Shows how much queue demand was successfully connected to an agent.',
      'نشان می‌دهد چه مقدار از تقاضای صف واقعاً به Agent متصل شده است.',
      'Answered count = CONNECT count. Answer rate = CONNECT / ENTERQUEUE × 100.',
      'تعداد پاسخ = شمارش CONNECT. نرخ پاسخ = CONNECT ÷ ENTERQUEUE × ۱۰۰.',
    ),
    unanswered: h(
      'Not answered in window',
      'پاسخ‌داده‌نشده در همین بازه',
      'Queue entries that do not have a CONNECT event inside the same selected window.',
      'ورودهای صفی که در همان بازه انتخاب‌شده Event اتصال CONNECT ندارند.',
      'Useful as a broad demand-not-answered indicator, but it can include calls whose final outcome crosses the report boundary.',
      'شاخص کلی تقاضای بدون پاسخ است، اما ممکن است تماس‌هایی را هم شامل شود که نتیجه نهایی‌شان از مرز زمانی گزارش عبور کرده است.',
      'Unanswered = max(0, ENTERQUEUE − CONNECT). Unanswered rate = Unanswered / ENTERQUEUE × 100.',
      'پاسخ‌داده‌نشده = max(0, ENTERQUEUE − CONNECT). نرخ آن = Unanswered ÷ ENTERQUEUE × ۱۰۰.',
    ),
    confirmedLost: h(
      'Confirmed lost calls',
      'تماس‌های از دست‌رفته قطعی',
      'Known terminal queue outcomes that ended without an agent connection.',
      'Outcomeهای نهایی شناخته‌شده صف که بدون اتصال به Agent تمام شده‌اند.',
      'Separating confirmed loss from generic unanswered calls avoids mixing known failures with boundary uncertainty.',
      'جداکردن Lost قطعی از Unanswered باعث می‌شود Outcomeهای معلوم با ابهام مرز زمانی مخلوط نشوند.',
      'Confirmed lost = ABANDON + EXITWITHTIMEOUT + EXITWITHKEY + EXITEMPTY + bounded agent/system terminal failures.',
      'Lost قطعی = ABANDON + EXITWITHTIMEOUT + EXITWITHKEY + EXITEMPTY + خطاهای نهایی محدود Agent/System.',
    ),
    callerAbandon: h(
      'Caller abandoned',
      'ترک صف توسط تماس‌گیرنده',
      'Calls where the caller left the queue before being connected to an agent.',
      'تماس‌هایی که تماس‌گیرنده قبل از اتصال به Agent صف را ترک کرده است.',
      'High caller abandonment can indicate long waits, poor queue messaging or demand exceeding staffing.',
      'بالا بودن این عدد می‌تواند نشانه انتظار زیاد، پیام‌رسانی نامناسب صف یا بیشتر بودن تقاضا از ظرفیت Agentها باشد.',
      'Count of ABANDON events. Rate = ABANDON / ENTERQUEUE × 100.',
      'از شمارش ABANDON به‌دست می‌آید. نرخ = ABANDON ÷ ENTERQUEUE × ۱۰۰.',
    ),
    timeout: h(
      'Queue timeout',
      'پایان مهلت انتظار صف',
      'Calls ended by the queue/system after the configured waiting limit expired.',
      'تماس‌هایی که پس از تمام‌شدن مهلت انتظار توسط Queue/System خاتمه یافته‌اند.',
      'This is operationally different from a caller choosing to abandon, so it is reported separately.',
      'این رفتار با ترک داوطلبانه تماس‌گیرنده فرق دارد و به همین دلیل جدا گزارش می‌شود.',
      'Count of EXITWITHTIMEOUT events. Rate = EXITWITHTIMEOUT / ENTERQUEUE × 100.',
      'از شمارش EXITWITHTIMEOUT به‌دست می‌آید. نرخ = EXITWITHTIMEOUT ÷ ENTERQUEUE × ۱۰۰.',
    ),
    exitKey: h(
      'Exited by menu key',
      'خروج با کلید منو',
      'Calls that left the queue through a configured caller key/menu action.',
      'تماس‌هایی که با فشردن کلید یا مسیر منوی تعریف‌شده از صف خارج شده‌اند.',
      'This is an intentional caller route and should not be mixed with abandon or timeout.',
      'این یک مسیر انتخابی تماس‌گیرنده است و نباید با Abandon یا Timeout یکی شود.',
      'Count of EXITWITHKEY events. Rate = EXITWITHKEY / ENTERQUEUE × 100.',
      'از شمارش EXITWITHKEY به‌دست می‌آید. نرخ = EXITWITHKEY ÷ ENTERQUEUE × ۱۰۰.',
    ),
    forcedExit: h(
      'Forced exit / empty queue',
      'خروج اجباری / صف بدون پاسخ‌دهنده',
      'Calls forced out because the queue could not provide an eligible agent path.',
      'تماس‌هایی که به‌دلیل نبود مسیر مناسب به Agent از صف خارج شده‌اند.',
      'This can indicate queue staffing, membership or availability configuration problems.',
      'می‌تواند نشانه مشکل در Staffing، Membership یا دسترس‌پذیری Agentهای صف باشد.',
      'Count of EXITEMPTY events. Rate = EXITEMPTY / ENTERQUEUE × 100.',
      'از شمارش EXITEMPTY به‌دست می‌آید. نرخ = EXITEMPTY ÷ ENTERQUEUE × ۱۰۰.',
    ),
    systemFailure: h(
      'Agent/system failure',
      'خطای پاسخ‌دهنده / سیستم',
      'Known terminal queue events associated with agent/system handling failure.',
      'Eventهای نهایی شناخته‌شده مربوط به خطای Agent یا System در پردازش صف.',
      'Keeping these events visible prevents technical failures from being hidden inside generic lost calls.',
      'نمایش جداگانه باعث می‌شود خطای فنی داخل Lost Call عمومی پنهان نشود.',
      'Current bounded category includes AGENTDUMP and SYSCOMPAT terminal events.',
      'دسته فعلی شامل Eventهای نهایی AGENTDUMP و SYSCOMPAT است.',
    ),
    unresolved: h(
      'Unresolved in this window',
      'بدون نتیجه نهایی در همین بازه',
      'Entries that are not answered and also do not reconcile to a known terminal lost outcome inside the window.',
      'ورودهایی که نه پاسخ داده شده‌اند و نه در همان بازه با Outcome نهایی Lost شناخته‌شده تطبیق دارند.',
      'This exposes report-boundary or custom-event uncertainty instead of silently calling it a loss.',
      'ابهام مرز بازه یا Event سفارشی را آشکار می‌کند و آن را بی‌دلیل Lost قطعی نمی‌نامد.',
      'Unresolved = max(0, Unanswered − Confirmed lost).',
      'Unresolved = max(0, Unanswered − Confirmed lost).',
    ),
    ringNoAnswer: h(
      'Agent ring-no-answer attempts',
      'تلاش زنگ به پاسخ‌دهنده بدون پاسخ',
      'Number of agent ring attempts that were not answered.',
      'تعداد دفعاتی که به Agent زنگ خورده ولی آن تلاش پاسخ داده نشده است.',
      'This is an attempt metric, not a lost-call metric. One caller can generate many RINGNOANSWER events before another agent answers.',
      'این KPI تعداد تلاش است، نه تعداد Lost Call. یک تماس می‌تواند چند RINGNOANSWER داشته باشد و در نهایت توسط Agent دیگری پاسخ داده شود.',
      'Count of RINGNOANSWER events. The normalized comparison is attempts per 100 ENTERQUEUE calls.',
      'از شمارش RINGNOANSWER به‌دست می‌آید. مقدار نرمال‌شده = تعداد Attempt به‌ازای هر ۱۰۰ ENTERQUEUE.',
    ),
    ringCanceled: h(
      'Canceled agent ring attempts',
      'تلاش زنگ لغوشده برای پاسخ‌دهنده',
      'Agent ring attempts that were canceled before completion.',
      'تلاش‌های زنگ به Agent که قبل از تکمیل لغو شده‌اند.',
      'Useful for diagnosing queue distribution behavior; it is not added to lost-call totals.',
      'برای تحلیل رفتار توزیع صف مفید است و به Lost Call اضافه نمی‌شود.',
      'Count of RINGCANCELED events.',
      'از شمارش Eventهای RINGCANCELED به‌دست می‌آید.',
    ),
    uniqueCallers: h(
      'Unique callers',
      'تماس‌گیرنده یکتا',
      'Number of different identified caller IDs that entered the selected queue scope.',
      'تعداد Caller IDهای متفاوتی که وارد محدوده صف‌های انتخاب‌شده شده‌اند.',
      'It separates “how many calls happened” from “how many different people/numbers generated those calls”.',
      'کمک می‌کند «تعداد تماس» را از «تعداد افراد/شماره‌های متفاوت» جدا ببینید.',
      'Distinct identified caller IDs across ENTERQUEUE events. In the combined total, the same caller appearing in multiple selected queues is counted once. Raw caller IDs are pseudonymized in memory and are not returned by the managerial KPI API.',
      'تعداد Caller ID یکتای شناسایی‌شده در ENTERQUEUE. در Total چندصفی، یک Caller مشترک فقط یک بار شمرده می‌شود. Caller ID خام در حافظه Pseudonymize می‌شود و در API مدیریتی برنمی‌گردد.',
    ),
    repeatCallers: h(
      'Repeat callers',
      'تماس‌گیرنده تکراری',
      'Unique identified callers that entered the selected queue scope at least twice during the report window.',
      'Callerهای یکتایی که در بازه گزارش حداقل دو بار وارد محدوده صف‌های انتخاب‌شده شده‌اند.',
      'Repeat demand can indicate unresolved customer needs, callbacks after abandonment, repeated service attempts or normal high-frequency usage.',
      'تماس تکراری می‌تواند نشانه حل‌نشدن نیاز، تماس مجدد بعد از Abandon، تلاش چندباره برای سرویس یا رفتار عادی پرتکرار باشد.',
      'Repeat caller = identified caller with ENTERQUEUE call count > 1. Combined total deduplicates the same caller across selected queues.',
      'Repeat Caller یعنی Caller شناسایی‌شده با بیش از یک ENTERQUEUE. در Total، Caller مشترک بین صف‌ها Deduplicate می‌شود.',
    ),
    repeatCallerRate: h(
      'Repeat-caller rate',
      'نرخ تماس‌گیرنده تکراری',
      'Share of identified unique callers who called more than once.',
      'درصد Callerهای یکتا و شناسایی‌شده‌ای که بیش از یک بار تماس گرفته‌اند.',
      'This shows whether repeat behavior affects a small minority or a large part of the caller population.',
      'نشان می‌دهد تماس تکراری مربوط به بخش کوچکی از Callerهاست یا قسمت بزرگی از آن‌ها.',
      'Repeat-caller rate = Repeat callers / Unique callers × 100.',
      'نرخ Caller تکراری = Repeat callers ÷ Unique callers × ۱۰۰.',
    ),
    avgCallsPerCaller: h(
      'Average calls per caller',
      'میانگین تماس به‌ازای هر تماس‌گیرنده',
      'Average queue-entry call count for each identified unique caller.',
      'میانگین تعداد ورود به صف برای هر Caller یکتای شناسایی‌شده.',
      'It provides a simple measure of contact frequency and makes high call volume easier to interpret.',
      'یک سنجه ساده از تکرار تماس است و کمک می‌کند حجم بالای تماس بهتر تفسیر شود.',
      'Average calls per caller = Identified ENTERQUEUE calls / Unique callers.',
      'میانگین تماس به‌ازای Caller = ENTERQUEUEهای دارای Caller ID ÷ Unique callers.',
    ),
    callsFromRepeat: h(
      'Calls from repeat callers',
      'تماس‌های ایجادشده توسط تماس‌گیرندگان تکراری',
      'Total number of calls generated by caller IDs that called more than once in the selected scope.',
      'کل تماس‌هایی که توسط Callerهایی ایجاد شده‌اند که در محدوده انتخاب‌شده بیش از یک بار تماس گرفته‌اند.',
      'This quantifies how much of the workload is created by repeat demand rather than one-time callers.',
      'مشخص می‌کند چه مقدار از بار صف ناشی از تقاضای تکراری است نه تماس‌گیرنده یک‌باره.',
      'Sum of ENTERQUEUE call counts for all identified callers whose call count > 1.',
      'مجموع تعداد ENTERQUEUE برای تمام Callerهای شناسایی‌شده‌ای که call count آن‌ها بیشتر از ۱ است.',
    ),
    repeatCallShare: h(
      'Repeat-call share',
      'سهم تماس‌های تکراری',
      'Percentage of identified queue-entry calls generated by repeat callers.',
      'درصد تماس‌های دارای Caller ID که توسط Callerهای تکراری ایجاد شده‌اند.',
      'A high value explains why call volume can be much larger than the number of unique callers.',
      'مقدار بالا توضیح می‌دهد چرا تعداد تماس می‌تواند خیلی بیشتر از تعداد Caller یکتا باشد.',
      'Repeat-call share = Calls from repeat callers / Identified ENTERQUEUE calls × 100.',
      'سهم تماس تکراری = Calls from repeat callers ÷ ENTERQUEUEهای دارای Caller ID × ۱۰۰.',
    ),
    callerIdCoverage: h(
      'Caller-ID coverage',
      'پوشش شناسایی Caller ID',
      'Percentage of queue-entry calls that had a usable caller identifier for caller-level KPIs.',
      'درصد تماس‌های ورودی صف که Caller ID قابل استفاده برای KPIهای تماس‌گیرنده داشته‌اند.',
      'Unique/repeat caller metrics are only as representative as this coverage.',
      'اعتبار KPIهای Caller یکتا/تکراری به میزان این پوشش وابسته است.',
      'Caller-ID coverage = Identified ENTERQUEUE calls / All ENTERQUEUE calls × 100.',
      'پوشش Caller ID = ENTERQUEUEهای دارای Caller ID ÷ کل ENTERQUEUE × ۱۰۰.',
    ),
    avgAnswer: h(
      'Average time to answer',
      'میانگین زمان تا پاسخ',
      'Average waiting time before calls that reached CONNECT were connected to an agent.',
      'میانگین زمان انتظار تماس‌هایی که در نهایت با CONNECT به Agent وصل شده‌اند.',
      'This reflects answer speed for successful connections, not the experience of abandoned calls.',
      'سرعت پاسخ برای تماس‌های موفق را نشان می‌دهد و تجربه تماس‌های Abandonشده را به‌تنهایی نمایندگی نمی‌کند.',
      'Weighted average of the CONNECT wait-time field across available samples.',
      'میانگین وزنی Wait Time مربوط به Eventهای CONNECT بر اساس نمونه‌های موجود.',
    ),
    avgWait: h(
      'Average caller wait in queue',
      'میانگین انتظار تماس‌گیرنده در صف',
      'Average available queue wait time across terminal queue outcomes included by the report.',
      'میانگین Wait Time موجود برای Outcomeهای نهایی صف که گزارش از آن‌ها استفاده می‌کند.',
      'Use it with answer/abandon rates because one average alone can hide different caller outcomes.',
      'آن را همراه نرخ پاسخ و Abandon تفسیر کنید چون یک میانگین به‌تنهایی تفاوت Outcomeها را پنهان می‌کند.',
      'Weighted average of available wait-time samples for CONNECT and supported terminal outcomes.',
      'میانگین وزنی نمونه‌های Wait Time موجود برای CONNECT و Outcomeهای نهایی پشتیبانی‌شده.',
    ),
    volumeChart: h(
      'Call volume comparison',
      'مقایسه حجم تماس',
      'Compares incoming, answered and confirmed-lost counts for each selected queue.',
      'تعداد تماس ورودی، پاسخ‌داده‌شده و Lost قطعی را بین صف‌های انتخاب‌شده مقایسه می‌کند.',
      'Use the chart for quick comparison and the table for exact values.',
      'برای مقایسه سریع از نمودار و برای عدد دقیق از جدول استفاده کنید.',
      'Uses the same KPI counts shown in the detailed table; it does not run another query.',
      'از همان KPIهای جدول استفاده می‌کند و Query جدیدی اجرا نمی‌کند.',
    ),
    lostChart: h(
      'Lost-call reason breakdown',
      'تفکیک علت تماس‌های از دست‌رفته',
      'Shows how non-answered outcomes are distributed across known lost reasons and unresolved remainder.',
      'نشان می‌دهد تماس‌های بدون پاسخ بین علت‌های Lost شناخته‌شده و بخش Unresolved چگونه تقسیم شده‌اند.',
      'Helps distinguish caller choice, queue timeout and technical/availability causes.',
      'کمک می‌کند انتخاب Caller، Timeout صف و علت‌های فنی/دسترس‌پذیری از هم جدا شوند.',
      'Each segment uses the corresponding outcome count divided by the queue unanswered count for visual composition.',
      'هر بخش نمودار از تعداد Outcome مربوطه نسبت به Unanswered همان صف ساخته می‌شود.',
    ),
    rateChart: h(
      'Answer and lost rates',
      'نرخ پاسخ و از دست‌رفته',
      'Compares answer rate and confirmed-lost rate between selected queues.',
      'نرخ پاسخ و Lost قطعی را بین صف‌های انتخاب‌شده مقایسه می‌کند.',
      'Useful for identifying queues with similar volume but different service outcomes.',
      'برای پیدا کردن صف‌هایی با حجم مشابه ولی Outcome متفاوت مفید است.',
      'Answer rate = Answered / Incoming. Confirmed-lost rate = Confirmed lost / Incoming.',
      'نرخ پاسخ = Answered ÷ Incoming. نرخ Lost قطعی = Confirmed lost ÷ Incoming.',
    ),
    timeChart: h(
      'Average queue timing',
      'میانگین زمان‌های صف',
      'Compares average time to answer and average caller wait between queues.',
      'میانگین زمان تا پاسخ و میانگین انتظار Caller را بین صف‌ها مقایسه می‌کند.',
      'Timing differences can reveal queues that need staffing, routing or policy review.',
      'اختلاف زمان‌ها می‌تواند صف‌های نیازمند بررسی Staffing، Routing یا Policy را مشخص کند.',
      'Uses the weighted timing KPIs already returned by the report.',
      'از KPIهای زمانی وزنی که گزارش قبلاً برگردانده استفاده می‌کند.',
    ),
    callerChart: h(
      'Unique and repeat callers',
      'تماس‌گیرندگان یکتا و تکراری',
      'Compares the number of unique identified callers with the subset that called more than once.',
      'تعداد Callerهای یکتا را با زیرمجموعه‌ای که بیش از یک بار تماس گرفته‌اند مقایسه می‌کند.',
      'Makes repeated demand visible without confusing it with total call volume.',
      'تقاضای تکراری را بدون مخلوط‌کردن با حجم کل تماس قابل مشاهده می‌کند.',
      'Unique = distinct identified caller IDs. Repeat = unique caller IDs with call count > 1.',
      'Unique = Caller ID یکتای شناسایی‌شده. Repeat = Callerهای یکتا با call count بیشتر از ۱.',
    ),
    attemptChart: h(
      'Agent ring attempts',
      'تلاش‌های زنگ به پاسخ‌دهنده',
      'Compares ring-no-answer and canceled ring attempts by queue.',
      'RINGNOANSWER و Ring Attemptهای لغوشده را بین صف‌ها مقایسه می‌کند.',
      'High attempt counts may indicate agent reachability, availability or queue-distribution behavior that deserves review.',
      'تعداد بالای Attempt می‌تواند نشانه مسئله دسترس‌پذیری Agent یا رفتار توزیع صف باشد.',
      'Direct count of RINGNOANSWER and RINGCANCELED events; these are not added to lost-call totals.',
      'شمارش مستقیم RINGNOANSWER و RINGCANCELED است و به Lost Call اضافه نمی‌شود.',
    ),
    generate: h(
      'Generate report',
      'ارائه گزارش',
      'Runs the selected queue-performance report with the current time and queue filters.',
      'گزارش عملکرد صف را با بازه و صف‌های فعلی اجرا می‌کند.',
      'Review the selected scope first because live-source reporting intentionally has safety bounds.',
      'قبل از اجرا محدوده را بررسی کنید چون گزارش روی Source عملیاتی عمداً Safety Bound دارد.',
      'The backend reads bounded, sequential source chunks and returns normalized aggregate KPIs.',
      'Backend داده را در Chunkهای محدود و متوالی می‌خواند و KPIهای Aggregate نرمال‌شده را برمی‌گرداند.',
    ),
    exportPdf: h(
      'Export report PDF',
      'خروجی PDF گزارش',
      'Creates a multi-page PDF from the report already loaded in the browser.',
      'از گزارشی که همین حالا در Browser لود شده PDF چندصفحه‌ای می‌سازد.',
      'Useful for management review and sharing a fixed report snapshot.',
      'برای بررسی مدیریتی و اشتراک یک Snapshot ثابت از گزارش مناسب است.',
      'No database query is executed. The browser renders summary, charts and per-queue detail pages from the loaded report state.',
      'هیچ Query جدیدی اجرا نمی‌شود. Browser Summary، نمودارها و صفحات تفکیکی صف را از Report State موجود می‌سازد.',
    ),
    exportExcel: h(
      'Export report Excel',
      'خروجی Excel گزارش',
      'Creates an XLSX with structured KPI cells and embedded report charts.',
      'فایل XLSX با Cellهای ساختاریافته KPI و نمودارهای Embedded می‌سازد.',
      'Use it when values need sorting, further analysis or spreadsheet-based review.',
      'برای Sort، تحلیل تکمیلی یا بررسی در Spreadsheet مناسب است.',
      'No database query is executed; the workbook uses the report response already loaded in the browser.',
      'Query جدیدی اجرا نمی‌شود و Workbook از Report Response موجود در Browser ساخته می‌شود.',
    ),
    exportDetails: h(
      'Export filtered call details Excel',
      'خروجی Excel ریز تماس‌های فیلترشده',
      'Exports one detailed row per queue entry using exactly the selected report time range and queues.',
      'برای هر ورود به صف، دقیقاً با همان بازه و صف‌های انتخاب‌شده یک ردیف جزئیات Excel خروجی می‌گیرد.',
      'Use it for call-by-call audit or reconciliation. The file contains caller numbers and call IDs, so treat it as sensitive operational data.',
      'برای Audit یا تطبیق تماس‌به‌تماس استفاده می‌شود. فایل شامل شماره Caller و Call ID است و داده عملیاتی حساس محسوب می‌شود.',
      'Detail is fetched only after explicit export action, through sequential bounded source slices. The browser caps the workbook at 75,000 queue calls and stores no generated file on the monitor backend.',
      'Detail فقط بعد از اقدام صریح Export و از Sliceهای محدود و متوالی Source خوانده می‌شود. Browser سقف ۷۵هزار تماس دارد و فایل روی Backend مانیتور ذخیره نمی‌شود.',
    ),
    callOutcomeReport: h(
      'Call outcome analytics',
      'تحلیل نتیجه تماس',
      'Summarizes CDR dispositions for the selected source-local time window.',
      'Dispositionهای CDR را در بازه زمانی انتخاب‌شده خلاصه می‌کند.',
      'Use it to understand broad call completion behavior before drilling into queue-specific causes.',
      'برای درک کلی وضعیت پایان تماس‌ها قبل از ورود به علت‌های تخصصی صف استفاده می‌شود.',
      'One aggregate query counts CDR rows by normalized disposition and averages CDR duration for the selected window.',
      'یک Query تجمیعی، ردیف‌های CDR را بر اساس Disposition نرمال‌شده می‌شمارد و میانگین Duration را در بازه انتخاب‌شده محاسبه می‌کند.',
    ),
    callOutcomeTotal: h(
      'Total calls',
      'کل تماس‌ها',
      'Total CDR records whose call start time falls inside the selected report window.',
      'کل ردیف‌های CDR که زمان شروع تماس آن‌ها داخل بازه گزارش است.',
      'This is the denominator for the overall answer ratio.',
      'این عدد مخرج نرخ کلی پاسخ است.',
      'COUNT(*) over CDR rows where calldate is between From and To.',
      'COUNT(*) روی ردیف‌های CDR که calldate آن‌ها بین From و To است.',
    ),
    callOutcomeAnswered: h(
      'Answered calls',
      'تماس‌های پاسخ‌داده‌شده',
      'CDR records whose normalized disposition is ANSWERED.',
      'ردیف‌های CDR که Disposition نرمال‌شده آن‌ها ANSWERED است.',
      'Shows how many calls reached an answered CDR outcome.',
      'نشان می‌دهد چند تماس به Outcome پاسخ‌داده‌شده رسیده‌اند.',
      'Count of disposition = ANSWERED.',
      'شمارش Disposition برابر ANSWERED.',
    ),
    callOutcomeNoAnswer: h(
      'No answer',
      'بدون پاسخ',
      'CDR records normalized to the no-answer disposition family.',
      'ردیف‌های CDR در خانواده Disposition بدون پاسخ.',
      'Useful for separating ringing/no-answer behavior from busy or technical failure.',
      'کمک می‌کند No Answer از Busy یا خطای فنی جدا دیده شود.',
      'Count of dispositions NO ANSWER, NOANSWER or NO_ANSWER.',
      'شمارش Dispositionهای NO ANSWER، NOANSWER یا NO_ANSWER.',
    ),
    callOutcomeBusy: h(
      'Busy',
      'مشغول',
      'CDR records whose normalized disposition is BUSY.',
      'ردیف‌های CDR که Disposition نرمال‌شده آن‌ها BUSY است.',
      'Shows calls that failed because the destination was busy rather than unanswered.',
      'تماس‌هایی را جدا می‌کند که مقصد Busy بوده، نه اینکه صرفاً پاسخ نداده باشد.',
      'Count of disposition = BUSY.',
      'شمارش Disposition برابر BUSY.',
    ),
    callOutcomeFailed: h(
      'Failed',
      'ناموفق',
      'CDR records mapped to supported technical-failure dispositions.',
      'ردیف‌های CDR که به Dispositionهای خطای فنی پشتیبانی‌شده نگاشت شده‌اند.',
      'Keeping technical failure separate helps avoid treating network/channel problems as caller behavior.',
      'جداکردن خطای فنی مانع می‌شود مشکل Network/Channel با رفتار Caller اشتباه شود.',
      'Count of FAILED, CONGESTION, CHANUNAVAIL or CHANNEL UNAVAILABLE.',
      'شمارش FAILED، CONGESTION، CHANUNAVAIL یا CHANNEL UNAVAILABLE.',
    ),
    callOutcomeUnknown: h(
      'Unknown disposition',
      'Disposition ناشناخته',
      'CDR rows whose disposition is not one of the recognized answer/no-answer/busy/failure categories.',
      'ردیف‌های CDR که Disposition آن‌ها در دسته‌های شناخته‌شده پاسخ، بدون پاسخ، Busy یا Failure نیست.',
      'Unknown values remain visible so the report never silently loses source categories.',
      'مقادیر ناشناخته نمایش داده می‌شوند تا هیچ دسته Source بی‌صدا حذف نشود.',
      'Unknown = Total − Answered − No answer − Busy − Failed.',
      'Unknown = Total − Answered − No Answer − Busy − Failed.',
    ),
    callOutcomeAnswerRatio: h(
      'Answer ratio',
      'نرخ پاسخ',
      'Share of all CDR calls in the window that have ANSWERED disposition.',
      'درصد کل تماس‌های CDR در بازه که Disposition آن‌ها ANSWERED است.',
      'Useful as a high-level completion ratio; queue-specific answer rate can use different queue-event semantics.',
      'یک نسبت کلی پاسخ است؛ نرخ پاسخ صف می‌تواند بر اساس Eventهای Queue تعریف متفاوتی داشته باشد.',
      'Answered / Total × 100.',
      'Answered ÷ Total × ۱۰۰.',
    ),
    callOutcomeAverageDuration: h(
      'Average duration',
      'میانگین مدت تماس',
      'Average CDR duration across all calls in the selected window.',
      'میانگین Duration در تمام ردیف‌های CDR داخل بازه انتخاب‌شده.',
      'This includes the source duration semantics for all dispositions, so interpret it together with outcome mix.',
      'Duration مطابق تعریف Source برای همه Dispositionهاست؛ آن را همراه ترکیب Outcomeها تفسیر کنید.',
      'AVG(CDR duration) for all rows in the selected window.',
      'AVG روی فیلد Duration تمام ردیف‌های CDR در بازه.',
    ),
    longWaitAbandon: h(
      'Long-wait abandons',
      'ترک صف پس از انتظار طولانی',
      'Caller-abandoned calls whose recorded wait time met or exceeded the selected threshold.',
      'تماس‌های ABANDON که Wait Time آن‌ها به Threshold انتخاب‌شده رسیده یا از آن بیشتر بوده است.',
      'Separates quick abandonments from cases where callers waited long enough to indicate queue pressure.',
      'Abandon سریع را از مواردی جدا می‌کند که Caller مدت قابل‌توجهی منتظر مانده و می‌تواند نشانه فشار صف باشد.',
      'Count of ABANDON events with wait seconds >= threshold minutes × 60.',
      'شمارش ABANDONهایی که Wait Seconds آن‌ها >= Threshold Minutes × ۶۰ است.',
    ),
    otherQueueOutcome: h(
      'Other queue outcomes',
      'سایر خروجی‌های صف',
      'Residual queue entries not represented by connected, caller-abandoned or queue-timeout counts in this focused chart.',
      'باقی‌مانده ورودهای صف که در این نمودار تخصصی داخل Connected، Caller Abandon یا Queue Timeout قرار نمی‌گیرند.',
      'Keeping a residual slice prevents the donut from implying that known categories explain every queue entry.',
      'وجود بخش باقیمانده مانع می‌شود نمودار به‌اشتباه نشان دهد دسته‌های شناخته‌شده تمام ورودهای صف را توضیح می‌دهند.',
      'Other = max(0, ENTERQUEUE − CONNECT − ABANDON − EXITWITHTIMEOUT).',
      'Other = max(0, ENTERQUEUE − CONNECT − ABANDON − EXITWITHTIMEOUT).',
    ),
    abandonmentChart: h(
      'Queue outcome distribution',
      'توزیع نتیجه تماس‌های صف',
      'Shows the relative composition of connected, caller-abandoned, timed-out and residual queue outcomes.',
      'ترکیب نسبی تماس‌های Connected، Abandon، Timeout و سایر Outcomeهای صف را نشان می‌دهد.',
      'Use it for quick part-to-whole comparison; exact values remain in the KPI cards.',
      'برای مقایسه سریع سهم Outcomeهاست و عدد دقیق در KPIها باقی می‌ماند.',
      'Chart segments use the already-loaded queue KPI counts; no additional source query is executed.',
      'بخش‌های نمودار از KPIهای لودشده استفاده می‌کنند و Query جدیدی اجرا نمی‌شود.',
    ),

    abandonmentThreshold: h(
      'Long-wait threshold',
      'آستانه انتظار طولانی',
      'Defines how many minutes an abandoned caller must have waited to count as a long-wait abandonment.',
      'مشخص می‌کند تماس‌گیرنده Abandonشده باید حداقل چند دقیقه منتظر مانده باشد تا Long-wait محسوب شود.',
      'It helps distinguish quick caller drop-offs from abandonment after meaningful waiting.',
      'کمک می‌کند قطع سریع Caller از Abandon بعد از انتظار قابل‌توجه جدا شود.',
      'Long-wait abandons = ABANDON events whose recorded wait time >= threshold × 60 seconds. Other queue KPIs do not change when this threshold changes.',
      'Long-wait = ABANDONهایی که Wait Time آن‌ها >= Threshold × ۶۰ ثانیه است. تغییر این Threshold سایر KPIهای صف را تغییر نمی‌دهد.',
    ),
    abandonmentRate: h(
      'Abandonment rate',
      'نرخ ترک صف',
      'Percentage of queue entries that ended with caller-driven ABANDON.',
      'درصد ورودهای صف که با ABANDON توسط تماس‌گیرنده تمام شده‌اند.',
      'Useful for monitoring caller patience and queue service pressure.',
      'برای سنجش تحمل Caller و فشار سرویس صف مفید است.',
      'ABANDON / ENTERQUEUE × 100.',
      'ABANDON ÷ ENTERQUEUE × ۱۰۰.',
    ),
    abandonWait: h(
      'Average wait before abandon',
      'میانگین انتظار پیش از ترک صف',
      'Average recorded waiting time for callers that abandoned the queue.',
      'میانگین Wait Time ثبت‌شده برای Callerهایی که صف را ترک کرده‌اند.',
      'It indicates whether abandonment tends to happen quickly or after a long wait.',
      'نشان می‌دهد Abandon معمولاً سریع رخ می‌دهد یا بعد از انتظار طولانی.',
      'Average of the ABANDON wait-time field for available samples.',
      'میانگین فیلد Wait Time در Eventهای ABANDON برای نمونه‌های موجود.',
    ),
    percentiles: h(
      'Wait percentiles',
      'صدک‌های زمان انتظار',
      'P50 and P90 describe the distribution of abandon wait times rather than only the average.',
      'P50 و P90 توزیع زمان انتظار قبل از Abandon را بهتر از یک میانگین ساده نشان می‌دهند.',
      'Percentiles help detect a long tail where a smaller group waits much longer than the average.',
      'کمک می‌کند Long Tail دیده شود؛ یعنی گروه کوچکی که خیلی بیشتر از میانگین منتظر می‌مانند.',
      'Exact nearest-rank percentiles are shown only when the complete abandonment sample fits the 1,000-row safety bound; otherwise they are omitted instead of estimated from a partial sample.',
      'صدک دقیق Nearest-rank فقط وقتی نمایش داده می‌شود که کل نمونه Abandon داخل سقف ۱۰۰۰ ردیفی جا شود؛ در غیر این صورت به‌جای تخمین از Sample ناقص، نمایش داده نمی‌شود.',
    ),
  },
} as const;
